const {chromium} = require(process.argv[2]);
const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path');
const base = process.argv[3], cookie = JSON.parse(fs.readFileSync(0, 'utf8'));
const {selectAuto, customPlan, selectCalendar, legacyCustomPlan, selectDates, dateRange} = require('./meal_planner_test_helpers.cjs');


(async () => {
    // Browser plugin not available: use installed Playwright and isolated real APIs.
    // Flow: add compact recipe rows -> shared plan -> one custom plan -> atomic save.
    const browser = await chromium.launch({channel:process.env.AI_PANTRY_BROWSER_CHANNEL || 'chrome',headless:true});
    try {
        const context = await browser.newContext({viewport:{width:1440,height:1000}});
        await context.addCookies([cookie]);
        const page=await context.newPage(), errors=[], posts=[];
        page.on('pageerror',e=>errors.push(e.message));
        page.on('console',m=>{if(['error','warning'].includes(m.type()))errors.push(m.text());});
        page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/batches/bulk'))posts.push(r.postDataJSON());});
        await page.goto(base+'/editor-qa');
        assert.equal(await page.title(),'AI Pantry — Meal Planner');
        assert.equal(page.url(),base+'/editor-qa');
        assert(await page.getByRole('heading',{name:'Meal Planner',exact:true}).isVisible());
        const dialog=page.locator('#mealPlannerDialog'), rows=dialog.locator('[data-meal-editor]');
        const row=i=>rows.nth(i), recipe=i=>row(i).locator('[name="recipe_url"]');
        const image=i=>row(i).locator('[data-meal-editor-image]'), imageLink=i=>row(i).locator('[data-meal-editor-image-link]');
        const loaded=async i=>{await image(i).waitFor({state:'visible'});assert(await image(i).evaluate(el=>el.complete&&el.naturalWidth>0));};
        const shared=dialog.locator('[data-meal-shared-form]');
        const custom=i=>customPlan(dialog,i).locator('[data-meal-editor-form]');
        const servings=form=>form.locator('[data-schedule-field="household"][data-meal="dinner"]');
        const note=form=>form.locator('[data-schedule-field="notes"]');
        const save=dialog.locator('[data-meal-batch-save]');
        const ready=()=>page.waitForFunction(()=>{const s=document.getElementById('mealPlannerDialog').mealPlanScheduleState;return !s.panel.ui.loading&&s.entries.every(e=>!e.panel?.ui.loading);});
        const open=async()=>{await page.getByRole('button',{name:'Add Meals',exact:true}).click();await ready();};
        const add=()=>dialog.locator('[data-meal-editor-add]').click();
        const notes=async(form,value)=>{if(!await note(form).isVisible())await form.locator('[data-schedule-section="notes"] > summary').click();await note(form).fill(value);};
        const screenshot=async name=>{const dir=process.env.AI_PANTRY_BROWSER_ARTIFACTS;if(dir){fs.mkdirSync(dir,{recursive:true});await page.screenshot({path:path.join(dir,name)});}};
        await open();
        assert.equal(await dialog.locator('[data-meal-editor-recipe-link]').count(),0);
        assert(await imageLink(0).isHidden());
        // A broken cover uses the same compact placeholder as an absent cover.
        await context.route('**/qa-static/images/ai-pantry-home-hero.png',route=>route.fulfill({status:200,contentType:'image/png',body:'invalid image'}));
        await selectAuto(recipe(0), 'recipe://bread');
        await row(0).getByText('No image',{exact:true}).waitFor({state:'visible'});assert(await image(0).isHidden());
        await context.unroute('**/qa-static/images/ai-pantry-home-hero.png');
        await selectAuto(recipe(0), 'recipe://soup');await loaded(0);
        assert.equal(await image(0).getAttribute('alt'),'Soup recipe photo');
        await selectAuto(recipe(0), 'recipe://bread');await loaded(0);
        assert.equal(await image(0).getAttribute('alt'),'Bread recipe photo');
        assert.equal(await dialog.getByRole('button',{name:'Customize',exact:true}).count(),0);
        assert.equal(await shared.locator('[data-schedule-mode]').count(),0);
        assert.equal(await shared.locator('[data-schedule-action="date"]').count(),42);
        assert(await row(0).locator('.app-meal-editor-actions').isHidden());
        await dialog.evaluate(e=>{e.scrollTop=0;});await screenshot('calendar-only-single-desktop.png');
        await page.setViewportSize({width:390,height:844});
        assert(await dialog.evaluate(e=>e.scrollWidth<=e.clientWidth+1));
        await screenshot('calendar-only-single-mobile.png');
        await page.setViewportSize({width:1440,height:1000});
        await shared.getByRole('button',{name:'Household total',exact:true}).click();
        await notes(shared,'Shared prep notes');
        await shared.locator('[data-schedule-section="prep"] > summary').click();
        await shared.locator('[data-schedule-action="add-prep"]').click();
        await shared.locator('[data-schedule-field="prep-date"]').fill('2026-10-04');
        await shared.locator('[data-schedule-field="prep-instruction"]').fill('Prepare all recipes');
        await add();await selectAuto(recipe(1), 'recipe://soup');
        await add();await selectAuto(recipe(2), 'recipe://rice');
        assert.equal(await rows.count(),3);
        assert.equal(await dialog.getByRole('button',{name:'Customize',exact:true}).count(),0);
        assert.equal(await dialog.locator('[data-meal-calendar-select]:visible').count(),0);
        assert.equal(await dialog.locator('.meal-schedule-calendar:visible').count(),1);
        await loaded(0);await loaded(1);
        assert.notEqual(await image(0).getAttribute('src'),await image(1).getAttribute('src'));
        assert(await image(2).isHidden());assert(await row(2).getByText('No image',{exact:true}).isVisible());
        // Recipe editor links keep the current planner and its unsaved draft open.
        const recipeLink=imageLink;
        for(const [i,value] of ['bread','soup','rice'].entries()) {
            const url=new URL(await recipeLink(i).getAttribute('href'),base);
            assert.equal(url.origin,base);assert.equal(url.pathname,'/recipe/edit');
            assert.equal(url.searchParams.get('url'),'recipe://'+value);
            assert.equal(url.searchParams.get('viewer_user_id'),'editor-qa');
            assert.equal(url.hash,'#recipe-preview');
            assert.equal(await recipeLink(i).getAttribute('target'),'_blank');
            assert.equal(await recipeLink(i).getAttribute('rel'),'noopener');
        }
        const beforeLink=await dialog.evaluate(el=>JSON.stringify(el.mealPlanScheduleState.panel.draft));
        // Isolate the editor document: this scenario verifies navigation and draft
        // preservation; recipe-editor routes have their own integration tests.
        await context.route('**/recipe/edit?**',route=>route.fulfill({status:200,contentType:'text/html',body:'<title>Recipe editor navigation</title><h1>Recipe editor</h1>'}));
        for(const index of [0,2]) {
            const link=recipeLink(index);
            await link.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');
            assert(await link.evaluate(el=>el.matches(':focus-visible')&&getComputedStyle(el).outlineStyle!=='none'));
            const popupPromise=page.waitForEvent('popup');await page.keyboard.press('Enter');
            const popup=await popupPromise;await popup.waitForLoadState();
            assert.equal(new URL(popup.url()).searchParams.get('url'),index===0?'recipe://bread':'recipe://rice');
            assert.equal(new URL(popup.url()).hash,'#recipe-preview');
            assert(await popup.evaluate(()=>window.opener===null));await popup.close();
        }
        await context.unroute('**/recipe/edit?**');
        assert(await dialog.isVisible());assert.equal(posts.length,0);
        assert.equal(await dialog.evaluate(el=>JSON.stringify(el.mealPlanScheduleState.panel.draft)),beforeLink);
        assert.equal(await dialog.locator('[data-meal-editor-form]').count(),1,'Only one scheduling form is mounted by default');
        assert.equal(await servings(shared).inputValue(),'8','Additional recipe yields must not overwrite the shared portions');
        assert.equal(await save.textContent(),'Save 1 Meal');
        await selectDates(shared, dateRange('2026-10-05', '2026-10-07'));
        assert.equal(await save.textContent(),'Save 3 Meals');
        assert.match(await dialog.locator('[data-meal-batch-help]').textContent(),/3 recipes · 3 meals · 24 servings/);
        const ids=await rows.evaluateAll(nodes=>nodes.map(n=>n.dataset.mealEditor));assert.equal(new Set(ids).size,3);
        // Ingredient selections remain recipe-specific, even for shared scheduling.
        for(let i=0;i<2;i++)await row(i).locator('[data-meal-ingredient-options] > summary').click();
        await row(1).getByRole('radio',{name:'Sunflower'}).check();
        assert(await row(0).getByRole('radio',{name:'Olive'}).isChecked());
        for(let i=0;i<2;i++)await row(i).locator('[data-meal-ingredient-options] > summary').click();
        await dialog.evaluate(e=>{e.scrollTop=0;});await screenshot('merged-meal-plan-dark.png');
        await page.evaluate(()=>document.documentElement.dataset.publicAuthTheme='light');
        assert.equal(await dialog.locator('.app-dialog-card').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)');
        await screenshot('merged-meal-plan-light.png');
        await page.evaluate(()=>document.documentElement.dataset.publicAuthTheme='dark');
        await page.setViewportSize({width:390,height:844});
        await screenshot('merged-meal-plan-mobile.png');
        const bounds=await dialog.evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth,height:e.getBoundingClientRect().height}));
        assert(bounds.scroll<=bounds.width+1);assert(bounds.height<=844);
        await page.setViewportSize({width:1440,height:1000});
        await legacyCustomPlan(row(1));
        assert.equal(await dialog.locator('[data-meal-editor-form]').count(),2);
        assert.equal(await servings(custom(1)).inputValue(),'2.666666');
        await selectDates(custom(1), ['2026-10-09']);
        await servings(custom(1)).fill('3');await notes(custom(1),'Soup only');
        await legacyCustomPlan(row(1));
        assert.equal(await custom(1).isVisible(),false);
        await selectDates(shared, dateRange('2026-10-05', '2026-10-06'));
        await servings(shared).fill('9');
        assert.equal(await save.textContent(),'Save 3 Meals');
        assert.match(await row(1).locator('[data-meal-editor-summary]').textContent(),/Custom plan.*1 day.*3 servings/);
        await legacyCustomPlan(row(1));
        await customPlan(dialog,1).locator('[data-meal-editor-reset]').click();
        assert.equal(await dialog.locator('[data-meal-editor-form]').count(),1);
        assert.equal(await save.textContent(),'Save 2 Meals');
        await legacyCustomPlan(row(1));
        assert.equal(await servings(custom(1)).inputValue(),'3','Reset rejoins the current shared settings');
        await selectDates(custom(1), []);
        await selectCalendar(dialog);
        await selectDates(shared, []);
        await legacyCustomPlan(row(1));await save.click();
        assert(await dialog.locator('[data-meal-shared-error]').isVisible());
        assert(await shared.isVisible());assert.match(await row(1).locator('[data-meal-editor-error]').textContent(),/Recipe 2:.*date/i);
        assert.equal(posts.length,0);assert.equal(await note(shared).inputValue(),'Shared prep notes');
        await selectDates(shared, dateRange('2026-10-05', '2026-10-06'));
        await selectCalendar(dialog,1);
        await selectDates(custom(1), ['2026-10-09']);
        await servings(custom(1)).fill('3');await notes(custom(1),'Soup only');
        await recipe(2).selectOption('');
        assert(await recipeLink(2).isHidden());assert.equal(await recipeLink(2).getAttribute('href'),null);
        assert(await imageLink(2).isHidden());assert.equal(await image(2).getAttribute('src'),null);
        await save.click();
        assert.match(await row(2).locator('[data-meal-editor-error]').textContent(),/Recipe 3: Please select a recipe/);
        await selectAuto(recipe(2), 'recipe://rice');
        assert.equal(new URL(await recipeLink(2).getAttribute('href'),base).searchParams.get('url'),'recipe://rice');
        // Removing the first row leaves both the shared plan and custom recipe intact.
        await row(0).locator('[data-meal-editor-remove]').click();
        assert.equal(await row(0).getAttribute('data-meal-editor'),ids[1]);
        assert.equal(new URL(await recipeLink(0).getAttribute('href'),base).searchParams.get('url'),'recipe://soup');
        assert.equal(await image(0).getAttribute('alt'),'Soup recipe photo');await loaded(0);
        assert.equal(await servings(custom(0)).inputValue(),'3');assert.equal(await servings(shared).inputValue(),'9');
        await add();await selectAuto(recipe(2), 'recipe://bread');await add();
        assert.equal(await save.textContent(),'Save 3 Meals','Blank row is excluded from the total');
        await save.click();await dialog.waitFor({state:'hidden'});
        assert.equal(posts.length,1);assert.equal(posts[0].batches.length,3);
        const plans=Object.fromEntries(posts[0].batches.map(b=>[b.recipe_url,b]));
        assert.equal(plans['recipe://soup'].allocations.length,1);assert.equal(plans['recipe://soup'].allocations[0].planned_servings,3);
        assert.equal(plans['recipe://soup'].ingredient_option_selections.oil,'sunflower');
        assert.equal(plans['recipe://soup'].prep_notes,'Soup only');
        assert.deepEqual(plans['recipe://bread'].allocations,plans['recipe://rice'].allocations);
        assert.equal(plans['recipe://rice'].allocations.length,2);assert.equal(plans['recipe://rice'].allocations[0].planned_servings,4.5);
        assert.equal(plans['recipe://rice'].prep_notes,'Shared prep notes');assert.equal(plans['recipe://rice'].prep_steps[0].instruction,'Prepare all recipes');
        const meals=async url=>(await(await context.request.get(base+'/api/meal-plan?recipe_url='+encodeURIComponent(url))).json()).meals;
        assert.equal((await meals('recipe://bread')).length,2);assert.equal((await meals('recipe://rice')).length,2);assert.equal((await meals('recipe://soup')).length,1);
        await open();assert.equal(await rows.count(),1);assert.equal(await recipe(0).inputValue(),'');
        await selectAuto(recipe(0), 'recipe://bread');await legacyCustomPlan(row(0));
        await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await open();
        assert.equal(await rows.count(),1);assert.equal(await dialog.locator('[data-meal-editor-form]').count(),1);assert.equal(await recipe(0).inputValue(),'');
        await selectAuto(recipe(0), 'recipe://soup');
        let release;const pending=new Promise(resolve=>release=resolve);
        await page.route('**/api/meal-plan/batches/bulk',async route=>{await pending;await route.continue();});
        await save.click();await page.waitForFunction(()=>document.getElementById('mealPlannerDialog').mealPlanScheduleState.saving);
        assert(await recipe(0).isDisabled());assert(await save.isDisabled());
        await page.keyboard.press('Escape');assert(await dialog.isVisible());
        await page.evaluate(()=>{void saveMealPlannerBatch();void saveMealPlannerBatch();});release();
        await dialog.waitFor({state:'hidden'});assert.equal(posts.length,2);await page.unroute('**/api/meal-plan/batches/bulk');
        await open();await selectAuto(recipe(0), 'recipe://soup');await save.click();
        await page.waitForFunction(()=>!document.getElementById('mealPlannerDialog').mealPlanScheduleState.saving);
        assert(await dialog.isVisible());assert.match(await row(0).locator('[data-meal-editor-error]').textContent(),/already planned/i);
        assert.equal((await meals('recipe://soup')).length,2);
        assert.deepEqual(errors.filter(e=>!e.includes('400 (BAD REQUEST)')),[]);
        console.log('PASS: compact rows, one shared plan, live inheritance, independent overrides/reset, validation, atomic payloads, cancel/reopen, duplicate protection, desktop/mobile/themes');
    } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
