const { chromium } = require(process.argv[2]);
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const base = process.argv[3];
const cookie = JSON.parse(fs.readFileSync(0, 'utf8'));
const artifacts = process.env.AI_PANTRY_BROWSER_ARTIFACTS;
(async () => {
    const browser = await chromium.launch({ channel: process.env.AI_PANTRY_BROWSER_CHANNEL || 'chrome', headless: true });
    try {
        const context = await browser.newContext({ viewport: { width: 1920, height: 1080 }, colorScheme: 'dark' });
        await context.addCookies([cookie]);
        const page = await context.newPage();
        page.setDefaultTimeout(10000);
        const errors = [], writes = [];
        page.on('pageerror', error => errors.push(error.message));
        page.on('console', message => { if (message.type() === 'error' && !message.text().includes('422')) errors.push(message.text()); });
        page.on('request', request => { if (request.method() === 'PUT' && request.url().includes('/api/master-data/units/')) writes.push(request.postDataJSON()); });
        const row = id => page.locator(`[data-unit-master-row][data-unit-id="${id}"]`);
        const a = () => row('volume_teaspoon'), b = () => row('volume_tablespoon');
        const name = r => r.locator('[data-unit-row-name]'), category = r => r.locator('[data-unit-row-category]');
        const save = r => r.locator('[data-unit-row-save]'), cancel = r => r.locator('[data-unit-row-cancel]');
        const form = page.locator('[data-unit-master-form]'), alias = form.locator('[data-unit-master-alias-input]');
        const group = r => r.evaluate(e => e.closest('[data-unit-master-category]').dataset.category);
        const screenshot = async filename => { if (artifacts) { fs.mkdirSync(artifacts, { recursive: true }); await page.screenshot({ path: path.join(artifacts, filename) }); } };
        let releaseScript;
        const scriptGate = new Promise(resolve => releaseScript = resolve);
        await page.route('**/js/units.js*', async route => { await scriptGate; await route.continue(); });
        const navigation = page.goto(base + '/admin/master-data/units');
        await name(a()).waitFor();
        assert.equal(await page.title(), 'Units');
        const registry = await page.locator('#ingredientUnitConfig').evaluate(e => JSON.parse(e.textContent));
        const controls = await page.locator('[data-unit-master-row]').evaluateAll(rows => rows.map(row => {
            const name = row.querySelector('[data-unit-row-name]'), category = row.querySelector('[data-unit-row-category]');
            return { id: row.dataset.unitId, nameTag: name?.tagName, type: name?.type, name: name?.value,
                selectTag: category?.tagName, category: category?.value, options: Array.from(category?.options || []).map(o => o.value),
                blocked: !name || !category || name.disabled || name.readOnly || category.disabled || name.hidden || category.hidden,
                pointer: getComputedStyle(name).pointerEvents };
        }));
        assert.equal(controls.length, 35);
        for (const control of controls) {
            const saved = registry.units.find(u => u.id === control.id);
            assert.equal(control.nameTag, 'INPUT'); assert.equal(control.type, 'text'); assert.equal(control.selectTag, 'SELECT');
            assert.equal(control.blocked, false); assert.notEqual(control.pointer, 'none');
            assert.equal(control.name, saved.name); assert.equal(control.category, saved.category);
            assert.deepEqual(control.options, registry.categories.map(c => c.key));
        }
        assert(await form.isHidden());
        await page.evaluate(() => document.fonts.ready);
        const height = (await a().boundingBox()).height;
        assert.equal(height, 68);
        await name(a()).fill('early draft'); await category(a()).selectOption('weight');
        releaseScript(); await navigation;
        await page.waitForFunction(() => !document.querySelector('[data-unit-id="volume_teaspoon"] [data-unit-row-save]').disabled);
        assert.equal(await name(a()).inputValue(), 'early draft');
        assert.equal(await category(a()).inputValue(), 'weight');
        assert.equal((await a().boundingBox()).height, height);
        await cancel(a()).click(); assert.equal(await name(a()).inputValue(), 'teaspoon'); assert.equal(await category(a()).inputValue(), 'volume');
        await page.mouse.move(0, 0); await page.locator('h1').click();
        const resting = await name(a()).evaluate(e => ({ border: getComputedStyle(e).borderTopColor, background: getComputedStyle(e).backgroundColor }));
        assert.equal(resting.border, 'rgba(0, 0, 0, 0)'); assert.equal(resting.background, 'rgba(0, 0, 0, 0)');
        await screenshot('units-inline-rest.png');
        await name(a()).focus(); assert.notEqual(await name(a()).evaluate(e => getComputedStyle(e).borderTopColor), resting.border);
        await page.keyboard.press('Tab'); await page.keyboard.press('Tab');
        assert(await category(a()).evaluate(e => e === document.activeElement));
        await page.keyboard.press('ArrowDown'); assert.equal(await category(a()).inputValue(), 'weight');
        assert.equal(writes.length, 0);
        await category(a()).selectOption('volume'); await name(a()).fill(' teaspoon '); assert(await save(a()).isDisabled()); assert(await cancel(a()).isEnabled()); await cancel(a()).click();
        await name(a()).fill(' TABLESPOON '); assert(await save(a()).isDisabled()); assert.match(await a().locator('[data-unit-row-name-error]').innerText(), /already accepted/);
        await name(a()).fill(' TBSP '); assert(await save(a()).isDisabled());
        await name(a()).fill('measuring teaspoon'); await category(a()).selectOption('weight'); await name(b()).fill('dessert spoon'); await category(b()).selectOption('count_package');
        assert(await save(a()).isEnabled()); assert(await save(b()).isEnabled());
        await cancel(b()).click(); assert.equal(await name(b()).inputValue(), 'tablespoon'); assert(await save(a()).isEnabled());
        await name(b()).fill('dessert spoon'); await category(b()).selectOption('count_package');
        await b().locator('[data-unit-master-edit-button]').click();
        assert.equal(await form.locator('[data-unit-master-name]:visible, [data-unit-master-category-select]:visible').count(), 0);
        await alias.fill('dessert spoons'); await alias.press('Enter');
        await form.getByRole('button', { name: 'Close aliases', exact: true }).click();
        await b().locator('[data-unit-master-edit-button]').click();
        assert(await form.getByRole('button', { name: 'Remove alias dessert spoons', exact: true }).isVisible());
        await a().locator('[data-unit-master-edit-button]').click();
        await alias.fill('tea measure'); await form.locator('[data-unit-master-alias-add]').click();
        await page.route('**/api/master-data/units/suggest', route => route.fulfill({ json: { ok: true, suggestion: { canonical_name: 'BAD AI NAME', category: 'optional', aliases: ['tsp', 'tsps', 'teaspoons', 'tea measure', 'AI teaspoon alias'] } } }), { times: 1 });
        await form.locator('[data-unit-master-ai-suggest]').click();
        await form.getByRole('button', { name: 'Remove alias AI teaspoon alias', exact: true }).waitFor();
        assert.equal(await name(a()).inputValue(), 'measuring teaspoon'); assert.equal(await category(a()).inputValue(), 'weight');
        await b().locator('[data-unit-master-edit-button]').click();
        let releaseSave;
        const saveGate = new Promise(resolve => releaseSave = resolve);
        await page.route('**/api/master-data/units/volume_teaspoon', async route => { await saveGate; await route.continue(); }, { times: 1 });
        await save(a()).click(); assert.equal(await group(a()), 'volume');
        assert(await name(b()).isEnabled()); await name(b()).fill('MEASURING TEASPOON');
        releaseSave();
        await page.waitForFunction(() => document.querySelector('[data-unit-master-row][data-unit-id="volume_teaspoon"]').closest('[data-unit-master-category]').dataset.category === 'weight');
        assert.equal(await name(a()).inputValue(), 'measuring teaspoon'); assert.equal(await group(a()), 'weight');
        assert.equal(await name(b()).inputValue(), 'MEASURING TEASPOON'); assert(await name(b()).evaluate(e => e === document.activeElement));
        assert.equal(await category(b()).inputValue(), 'count_package'); assert(await save(b()).isDisabled());
        assert.match(await b().locator('[data-unit-row-name-error]').innerText(), /already accepted/);
        assert(await form.getByRole('button', { name: 'Remove alias dessert spoons', exact: true }).isVisible());
        assert.equal(await form.evaluate(e => e.previousElementSibling.dataset.unitId), 'volume_tablespoon');
        assert.equal(await a().locator('.unit-master-source-badge').innerText(), 'Built-in');
        assert.match(await a().locator('.unit-master-usage').innerText(), /3\s+recipes/);
        assert.match(await page.locator('[data-category="volume"] [data-unit-master-category-count-label]').innerText(), /^8 units$/);
        assert.match(await page.locator('[data-category="weight"] [data-unit-master-category-count-label]').innerText(), /^5 units$/);
        const savedResponse = await context.request.get(base + '/api/master-data/units');
        const savedRegistry = (await savedResponse.json()).registry;
        assert.equal(savedRegistry.units.filter(u => u.category === 'weight').at(-1).id, 'volume_teaspoon');
        for (const key of ['volume', 'weight']) {
            const units = savedRegistry.units.filter(u => u.category === key);
            assert.deepEqual(units.map(u => u.sort_order), units.map((_, i) => i));
        }
        assert.equal(writes.length, 1); assert(writes[0].aliases.includes('tea measure'));
        await name(b()).fill('dessert spoon revised'); await save(b()).click(); await form.waitFor({ state: 'hidden' });
        assert.equal(await group(b()), 'count_package');
        await name(a()).fill('cancel draft'); await category(a()).selectOption('optional');
        await a().locator('[data-unit-master-edit-button]').click(); await alias.fill('cancel alias');
        await cancel(a()).click(); assert(await form.isHidden());
        assert.equal(await name(a()).inputValue(), 'measuring teaspoon'); assert.equal(await category(a()).inputValue(), 'weight');
        await a().locator('[data-unit-master-edit-button]').click(); await alias.fill('cancel timing alias'); await alias.press('Enter');
        const cup = row('volume_cup'); await cup.locator('[data-unit-master-edit-button]').click(); await name(cup).fill('cancel timing cup');
        let releaseAnotherSave;
        const anotherGate = new Promise(resolve => releaseAnotherSave = resolve);
        await page.route('**/api/master-data/units/volume_teaspoon', async route => { await anotherGate; await route.continue(); }, { times: 1 });
        await save(a()).click(); await cancel(cup).click(); assert(await form.isHidden()); assert.equal(await name(cup).inputValue(), 'cup');
        releaseAnotherSave();
        await page.waitForFunction(() => document.querySelector('[data-unit-master-row][data-unit-id="volume_teaspoon"]').getAttribute('aria-busy') === 'false');
        await name(a()).fill('server conflict draft');
        await page.route('**/api/master-data/units/volume_teaspoon', route => route.fulfill({ status: 422, json: { ok: false, error: 'Name conflict.', errors: { canonical_name: 'Already assigned to another unit.' } } }), { times: 1 });
        await save(a()).click(); await a().locator('[data-unit-row-name-error]').waitFor({ state: 'visible' });
        assert.equal(await name(a()).inputValue(), 'server conflict draft'); assert(await save(a()).isDisabled()); assert.equal(await group(a()), 'weight');
        await cancel(a()).click();
        await name(b()).fill('filtered draft'); await page.locator('[data-unit-master-search]').fill('measuring teaspoon');
        assert(await b().isHidden()); await page.locator('[data-unit-master-search]').fill(''); assert.equal(await name(b()).inputValue(), 'filtered draft');
        await cancel(b()).click();
        await page.reload(); assert.equal(await name(a()).inputValue(), 'measuring teaspoon'); assert.equal(await category(a()).inputValue(), 'weight');
        assert.equal(await name(b()).inputValue(), 'dessert spoon revised'); assert.equal(await category(b()).inputValue(), 'count_package');
        await name(b()).fill('reordering draft');
        let ordered = page.waitForResponse(r => r.request().method() === 'PATCH' && r.url().endsWith('/units/volume_teaspoon'));
        await a().locator('[data-unit-master-drag-handle]').press('Home'); assert((await ordered).ok());
        await page.waitForFunction(() => document.querySelector('[data-unit-id="volume_teaspoon"] [data-unit-master-order-number]').textContent === '1');
        assert.equal(await name(b()).inputValue(), 'reordering draft');
        ordered = page.waitForResponse(r => r.request().method() === 'PATCH' && r.url().endsWith('/units/volume_teaspoon'));
        await a().locator('[data-unit-master-drag-handle]').dragTo(row('weight_gram'), { targetPosition: { x: 50, y: 60 } });
        assert((await ordered).ok());
        assert.equal(await name(b()).inputValue(), 'reordering draft'); await cancel(b()).click();
        await a().evaluate(e => e.scrollIntoView({ block: 'center' })); await name(a()).fill('desktop draft');
        await screenshot('units-inline-draft.png'); await cancel(a()).click();
        await page.setViewportSize({ width: 390, height: 844 }); await a().evaluate(e => e.scrollIntoView({ block: 'center' }));
        await name(a()).fill('mobile draft'); await category(a()).selectOption('volume');
        assert(await save(a()).isEnabled()); assert(await form.isHidden());
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
        const saveBox = await save(a()).boundingBox(), cancelBox = await cancel(a()).boundingBox();
        assert(saveBox.x + saveBox.width <= cancelBox.x, 'Mobile Save and Cancel must not overlap');
        assert.equal(saveBox.y, cancelBox.y);

        await name(a()).evaluate(e => e.scrollIntoView({ block: 'center' })); await screenshot('units-inline-mobile.png');
        await cancel(a()).click(); assert.equal(await name(a()).inputValue(), 'measuring teaspoon');
        await page.setViewportSize({ width: 1920, height: 1080 });
        await page.locator('[data-unit-master-add-button]').first().click();
        await form.locator('[data-unit-master-name]').fill('test scoop'); await form.locator('[data-unit-master-category-select]').selectOption('volume');
        await form.locator('[data-unit-master-save]').click(); await form.waitFor({ state: 'hidden' });
        assert.equal(await page.locator('[data-unit-row-name]').count(), 36);
        assert.deepEqual(errors, []);
        console.log('PASS enabled SSR DOM, delayed-script typing, keyboard, real inline editing, independent drafts, alias/AI integration, conflicts, row saves/cancel, cross-category ordering/counts, references, refresh, desktop/mobile, Add Unit, console');
    } finally { await browser.close(); }
})().catch(error => { console.error(String(error.message).split('Call log:')[0]); console.error(String(error.stack || '').split('\n').filter(line => /^\s+at /.test(line)).slice(0, 6).join('\n')); process.exitCode = 1; });
