@echo off

cd /d D:\GitHub\recipe-shopping-system-A

echo Starting Flask app...

set SHOPPING_APP_PORT=5056
set PRODUCT_SEARCH_WORKERS=2
set PRODUCT_DETAIL_LIMIT_PER_STORE=4
set PRODUCT_AI_ANALYSIS_LIMIT_PER_STORE=2
set PRODUCT_FINAL_SELECTION_CANDIDATES=18
set PRODUCT_AI_BROWSER_WAIT_SECONDS=4
start http://127.0.0.1:%SHOPPING_APP_PORT%

py -3.11 app.py
